"""add status column to pipeline_run

Revision ID: 087f1c8b75f4
Revises: b2b084e75df3
Create Date: 2025-05-09 19:25:27.745520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087f1c8b75f4'
down_revision = 'b2b084e75df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
