"""add pipeline reesult table

Revision ID: 625c861a6383
Revises: 7d98bdb1ae5d
Create Date: 2025-05-12 16:54:29.430516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625c861a6383'
down_revision = '7d98bdb1ae5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_pipeline_result_run_id', sa.Integer(), nullable=False),
    sa.Column('gene_stable_id', sa.String(length=128), nullable=False),
    sa.Column('gene_type', sa.String(length=64), nullable=False),
    sa.Column('gene_name', sa.String(length=128), nullable=False),
    sa.Column('hgnc_name', sa.String(length=128), nullable=True),
    sa.Column('hgnc_id', sa.String(length=128), nullable=True),
    sa.Column('panther_id', sa.String(length=128), nullable=True),
    sa.Column('tigrfam_id', sa.String(length=128), nullable=True),
    sa.Column('wikigene_name', sa.String(length=256), nullable=True),
    sa.Column('gene_description', sa.String(length=1024), nullable=True),
    sa.Column('pid_suffix', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fk_pipeline_result_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_result')
    # ### end Alembic commands ###
