"""initial migration

Revision ID: b2df9a38497e
Revises: 
Create Date: 2025-06-29 20:10:29.799080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2df9a38497e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_stable_id', sa.String(length=50), nullable=False),
    sa.Column('gene_type', sa.String(length=50), nullable=True),
    sa.Column('gene_name', sa.String(length=100), nullable=True),
    sa.Column('hgnc_name', sa.String(length=100), nullable=True),
    sa.Column('hgnc_id', sa.String(length=50), nullable=True),
    sa.Column('hgnc_id_exists', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gene_gene_stable_id'), ['gene_stable_id'], unique=False)

    op.create_table('gene_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_stable_id', sa.String(length=50), nullable=False),
    sa.Column('hgnc_id', sa.String(length=50), nullable=True),
    sa.Column('panther_id', sa.String(length=100), nullable=True),
    sa.Column('tigrfam_id', sa.String(length=100), nullable=True),
    sa.Column('wikigene_name', sa.String(length=100), nullable=True),
    sa.Column('gene_description', sa.Text(), nullable=True),
    sa.Column('pid_suffix', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gene_annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gene_annotation_gene_stable_id'), ['gene_stable_id'], unique=False)

    op.create_table('researcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researcher_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_researcher_researcher_name'), ['researcher_name'], unique=True)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['researcher.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('pipeline_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=140), nullable=False),
    sa.Column('pipeline_type', sa.String(length=140), nullable=False),
    sa.Column('fk_pipeline_run_researcher_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('output_dir', sa.String(length=120), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['fk_pipeline_run_researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_run_output_dir'), ['output_dir'], unique=True)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_researcher_id'), ['researcher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    op.create_table('pipeline_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_pipeline_result_run_id', sa.Integer(), nullable=False),
    sa.Column('gene_stable_id', sa.String(length=128), nullable=False),
    sa.Column('gene_type', sa.String(length=64), nullable=False),
    sa.Column('gene_name', sa.String(length=128), nullable=False),
    sa.Column('hgnc_name', sa.String(length=128), nullable=True),
    sa.Column('hgnc_id', sa.String(length=128), nullable=True),
    sa.Column('panther_id', sa.String(length=128), nullable=True),
    sa.Column('tigrfam_id', sa.String(length=128), nullable=True),
    sa.Column('wikigene_name', sa.String(length=256), nullable=True),
    sa.Column('gene_description', sa.String(length=1024), nullable=True),
    sa.Column('pid_suffix', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fk_pipeline_result_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_result')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_researcher_id'))

    op.drop_table('post')
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_run_output_dir'))

    op.drop_table('pipeline_run')
    op.drop_table('followers')
    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researcher_researcher_name'))
        batch_op.drop_index(batch_op.f('ix_researcher_email'))

    op.drop_table('researcher')
    with op.batch_alter_table('gene_annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gene_annotation_gene_stable_id'))

    op.drop_table('gene_annotation')
    with op.batch_alter_table('gene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gene_gene_stable_id'))

    op.drop_table('gene')
    # ### end Alembic commands ###
